services:
  seanorepo-fly-stack:
    build:
      # monorepo root as build context
      context: ../..
      # Dockerfile path relative to *context*
      dockerfile: utils/fly-io/dockerfile
    ports:
      - "8080:8080"   # nginx gateway
      - "6000:5000"   # seanmizen.com (local:container)
      - "6010:5010"   # seanscards FE
      - "6011:5011"   # seanscards BE
      - "6020:5020"   # carolinemizen FE
      - "6021:5021"   # carolinemizen BE
      - "6030:5030"   # planning-poker FE
      - "6031:5031"   # planning-poker BE
    container_name: seanorepo-fly-stack
